### ISSUE TITLE
Code and checkpoints release

### ISSUE THREAD

**Issue by VladimirYugay** [isl-org/PhotorealismEnhancement#1]
Hey there,

Thanks for your work, it looks amazing. 

When will the code and the checkpoints be released?

**Comment by HelixNGC7293** [comment]
Can't wait to try it out!

**Comment by lgonz041** [comment]
Yup same here!

**Comment by pedrolucastp** [comment]
Amazing work! Could you
Combine different images database, like using macro photos for better understanding of textures, lighting reflection

**Comment by dailafing** [comment]
Ditto! - I'm really excited to try this out for myself!
Once the code is released, I wouldn't be surprised if Intel's value goes up...
Please release the current Code & Checkpoints!!!
As soon as it's on GitHub here, it'll be amazing to see what contributions or forks come from it....
Plllleeeassssseeeeeeee!!!!!

**Comment by fangdaoyou** [comment]
Amazing work!
Waiting for code!

**Comment by darthnithin** [comment]
#3

**Comment by soheilAppear** [comment]
> Hey there,
> 
> Thanks for your work, it looks amazing.
> 
> When will the code and the checkpoints be released?

I cant wait to see the code! It is one of the most impressive things that I've seen in the past few years!

**Comment by srrichter** [comment]
Hi all,
thanks for your patience! We are in the final stages of the approval process and expect to have a release before the end of the year. Due to legal issues we will not be able to release checkpoints or the full dataset. This should not prevent you from training you own version though -- our experiments showed that strong enhancements are possible with a smaller number of G-buffers, using segmentation labels, or even without the G-buffers. For experiments with G-buffers we recommend looking  into capturing your own dataset. Several other research projects have demonstrated how to do this and have released code for it.

**Comment by dbr2019** [comment]
How's it going?
