### ISSUE TITLE
Dataset release

### ISSUE THREAD

**Issue by ydblg** [isl-org/PhotorealismEnhancement#10]
Hello. First, congratulations on the great work and the amazing results. Will the dataset used for training be released ? If yes, do you have a time window ?

**Comment by ferric123** [comment]
Same question here, could you please release the training data?

**Comment by srrichter** [comment]
Hi,
thanks for the kind words. As it appears now, we will unfortunately not be able to release the full dataset, i.e. all of the G-buffers due to legal issues. This should not keep you from training your own models with the code, though -- several other projects have demonstrated how G-buffers can be captured from games and have released code for doing so. Also, please keep in mind that the G-buffers are only one component in the whole pipeline and strong results can be achieved even when just using rendered images without any G-buffers (as demonstrated in our ablation study in the paper).
