### ISSUE TITLE
Number of image channels the provided G-buffers contain

### ISSUE THREAD

**Issue by hodakagoto** [isl-org/PhotorealismEnhancement#18]
Hi, very interesting work!
I have a question.
In `epe/dataset/pfd.py`, it says that number of channels G-buffers contain is `{'fake':32, 'all':26, 'img':0, 'no_light':17, 'geometry':8}`.
Where do these numbers come from?
I looked [Playing for Data](https://bitbucket.org/visinf/projects-2016-playing-for-data) but couldn't find them.
Thank you for any help.

**Comment by srrichter** [comment]
Hi,

these numbers are not related to the publicly available data (only images and label maps are available). The numbers relate to the G-buffers we used for training (see Fig. 5 in the paper for samples). Without access to these G-buffers, it is for the PlayingForData dataset only possible to work with just image data (i.e., 0 channels) or create some fake data from e.g. VGG features (i.e. the 32, which are simply subsampled from a VGG-16 feature map with a larger channel width). Since the exact same G-buffers are not publicly available, these numbers and the pfd.py should rather be taken as a guide for setting up your own dataset (and game).

For (your own) game data, the general intuition is that all data about a scene that is provided explicitly through G-buffers does not need to be learned by the network from image data. And learning complex lighting or material properties just from images can require quite a large number of frames and training iterations, if it is even learned at all without proper supervision.

**Comment by hodakagoto** [comment]
Thank you very much for your prompt reply!
In the paper, it says that you extract G-buffers that provide information about geometric structure (**surface normals, depth**), materials (**shader IDs, albedo, specular intensity, glossiness, transparency**), and lighting (**approximate irradiance and emission, sky, bloom**).
Those will be 11 channels in total, what other information does `all:26` contain?

**Comment by TiPEX360** [comment]
> proxim
 I believe the idea is that some of the g-buffers you mentioned (e.g. albedo/normal) contain more than just one channel e.g. albedo and normal contain RGB and XYZ channels each respectively. I can't know for certain, but even single channel buffers like depth could have been encoded as a 3-channel image. Depending on the specific implementation choices made, all of these channels could quite easily add up to 26, although I agree it would be useful to know exactly how these 26 channels have been distributed between the g-buffers and in what order. Perhaps @srrichter could shed some more light?
