### ISSUE TITLE
could this be added for retro games like Dolphin emulator? or retroarch shaders?

### ISSUE THREAD

**Issue by Littlemac123** [isl-org/PhotorealismEnhancement#2]
I  would love to see this tested for games like metroid prime and pikmin

**Comment by srrichter** [comment]
> I would love to see this tested for games like metroid prime and pikmin

What would you use as real-world reference data?

**Comment by valfonso678** [comment]
Photorealistic Blender Renders.

**Comment by IceHacks** [comment]
lol

**Comment by darthnithin** [comment]
> 
> 
> Photorealistic Blender renders.

I suppose that would be a way to try to get cheap (computer resource wise) and perhaps faster renders.

**Comment by srrichter** [comment]
In case of using Blender renders as the target, you could get by with a much simpler setup, actually. Since direct supervision would be available you would not need the sampling procedure and the perceptual discriminator. You could use just the LPIPS or some related perceptual loss for supervision and pair low-quality images with rendered data directly.
